{
  "name": "wesley-counter",
  "main": "counter.js",
  "compatibility_date": "2024-01-01",
  "kv_namespaces": [
    {
      "binding": "COUNTERS",
      "id": "7607eab50ebd4d13bab04e7238d9d32c"
    }
  ]
}
